#base image
FROM node:10.16.0-alpine

#copy files

WORKDIR /app
COPY ./ReactFirstExcercise/frontend/package.json .
#install dependencies
RUN npm install
COPY ./ReactFirstExcercise/frontend/ .

EXPOSE 3000

CMD ["npm", "start"]